var data = {
    "retCode": "000000",
    "retMsg": null,
    "data": {
        "sumMap": {
            "sumCC": "0.00",
            "sumGiftConsume": "22841.61",
            "sumCA": "195521.33",
            "sumConsume": "104621.45",
            "sumEx": "190.00"
        },
        "totalSize": "413",
        "data": [
            {
                "id": "8752752929074307191",
                "date": "2017-06-02",
                "customerName": "周洋洋(Z100001)",
                "customerType": "普通会员",
                "storeName": "天子娇子嘉信店",
                "code": "201706020945855268715593",
                "serverProduct": "超声刀下颌",
                "serverNumber": "1",
                "roomName": "-",
                "useCard": "超声刀下颌(test3测试)",
                "storeConsume": "0.00",
                "giftConsume": "0.00",
                "openEmp": "莫*盈",
                "des": "",
                "workEmpList": [
                    {
                        "empName": "闰*",
                        "postType": "高级技师",
                        "consumeAch": "0.00",
                        "commission": "0.00",
                        "extrawage": "0.00",
                        "isAppont": "0"
                    }
                ],
                "orderType": "2",
                "inviters": null,
                "sourceName": null,
                "evaluateValue": null,
                "evaluteDes": "-",
                "isFix": "0",
                "advisor": "莫*盈",
                "beautician": "闰*",
                "category": "其他美容项目/CSD/V超声刀下颌",
                "brandStoreName": null
            },
            {
                "id": "8752752929070936342",
                "date": "2017-05-24",
                "customerName": "1*7(1000002)",
                "customerType": "-",
                "storeName": "天子娇子嘉信店",
                "code": "201705240946251115889011",
                "serverProduct": "腋下T1",
                "serverNumber": "1",
                "roomName": "-",
                "useCard": "腋下5次T1",
                "storeConsume": "276.00",
                "giftConsume": "0.00",
                "openEmp": "天*娇",
                "des": "",
                "workEmpList": [
                    {
                        "empName": "苏*蝶",
                        "postType": "高级技师",
                        "consumeAch": "276.00",
                        "commission": "0.00",
                        "extrawage": "0.00",
                        "isAppont": "0"
                    }
                ],
                "orderType": "0",
                "inviters": null,
                "sourceName": null,
                "evaluateValue": null,
                "evaluteDes": "-",
                "isFix": "0",
                "advisor": "莫*盈",
                "beautician": "-",
                "category": "超冰脱毛",
                "brandStoreName": null
            },
            {
                "id": "8752752929040918746",
                "date": "2017-05-22",
                "customerName": "1*3(1000001)",
                "customerType": "-",
                "storeName": "天子娇子嘉信店",
                "code": "201705221603185752535334",
                "serverProduct": "泡浴养生",
                "serverNumber": "1",
                "roomName": "-",
                "useCard": "泡浴养生",
                "storeConsume": "6666.00",
                "giftConsume": "0.00",
                "openEmp": "莫*盈",
                "des": "",
                "workEmpList": [
                    {
                        "empName": "黄*兰",
                        "postType": "高级技师",
                        "consumeAch": "6666.00",
                        "commission": "0.00",
                        "extrawage": "0.00",
                        "isAppont": "0"
                    }
                ],
                "orderType": "0",
                "inviters": null,
                "sourceName": null,
                "evaluateValue": null,
                "evaluteDes": "-",
                "isFix": "0",
                "advisor": "莫*盈",
                "beautician": "-",
                "category": "不确定的品类",
                "brandStoreName": null
            },
            {
                "id": "8787426657287862985",
                "date": "2017-03-27",
                "customerName": "杜*青(D20002)",
                "customerType": "体验客",
                "storeName": "天子娇子嘉信店",
                "code": "201703271512595125558681",
                "serverProduct": "AF1清新清爽补水护理",
                "serverNumber": "1",
                "roomName": "A3",
                "useCard": "3880元任选480项目20次",
                "storeConsume": "144.00",
                "giftConsume": "0.00",
                "openEmp": "莫*盈",
                "des": "",
                "workEmpList": [
                    {
                        "empName": "苏*蝶",
                        "postType": "高级技师",
                        "consumeAch": "144.00",
                        "commission": "0.00",
                        "extrawage": "0.00",
                        "isAppont": "0"
                    },
                    {
                        "empName": "陈*香",
                        "postType": "高级顾问",
                        "consumeAch": "144.00",
                        "commission": "0.00",
                        "extrawage": "0.00",
                        "isAppont": "0"
                    }
                ],
                "orderType": "0",
                "inviters": null,
                "sourceName": null,
                "evaluateValue": null,
                "evaluteDes": "-",
                "isFix": "0",
                "advisor": "陈*香",
                "beautician": "-",
                "category": "面部护理/AF日本奥比虹品牌",
                "brandStoreName": null
            },
            {
                "id": "8787426657198988199",
                "date": "2017-03-27",
                "customerName": "伍*芬(W20010)",
                "customerType": "普通会员",
                "storeName": "天子娇子嘉信店",
                "code": "201703271439503869147205",
                "serverProduct": "YF9魔镜细胞紧致护肤护理",
                "serverNumber": "1",
                "roomName": "A2",
                "useCard": "YF9魔镜细胞紧致活化护理10次",
                "storeConsume": "245.10",
                "giftConsume": "0.00",
                "openEmp": "莫*盈",
                "des": "",
                "workEmpList": [
                    {
                        "empName": "吴*飞",
                        "postType": "高级技师",
                        "consumeAch": "245.10",
                        "commission": "0.00",
                        "extrawage": "0.00",
                        "isAppont": "0"
                    },
                    {
                        "empName": "陈*香",
                        "postType": "高级顾问",
                        "consumeAch": "245.10",
                        "commission": "0.00",
                        "extrawage": "0.00",
                        "isAppont": "0"
                    }
                ],
                "orderType": "0",
                "inviters": null,
                "sourceName": null,
                "evaluateValue": null,
                "evaluteDes": "-",
                "isFix": "0",
                "advisor": "陈*香",
                "beautician": "吴*飞",
                "category": "抗衰老/YF全方位面部抗衰仪器",
                "brandStoreName": null
            },
            {
                "id": "8787426654183312295",
                "date": "2017-03-26",
                "customerName": "张*卿(Z20054)",
                "customerType": "普通会员",
                "storeName": "天子娇子嘉信店",
                "code": "201703262001632098146747",
                "serverProduct": "(C15)刮痧",
                "serverNumber": "1",
                "roomName": "A2",
                "useCard": "C项卡180以内任选50次",
                "storeConsume": "50.00",
                "giftConsume": "0.00",
                "openEmp": "莫*盈",
                "des": "",
                "workEmpList": [
                    {
                        "empName": "陈*琴",
                        "postType": "高级技师",
                        "consumeAch": "50.00",
                        "commission": "0.00",
                        "extrawage": "0.00",
                        "isAppont": "0"
                    },
                    {
                        "empName": "莫*盈",
                        "postType": "高级顾问",
                        "consumeAch": "50.00",
                        "commission": "0.00",
                        "extrawage": "0.00",
                        "isAppont": "0"
                    }
                ],
                "orderType": "0",
                "inviters": null,
                "sourceName": null,
                "evaluateValue": null,
                "evaluteDes": "-",
                "isFix": "0",
                "advisor": "莫*盈",
                "beautician": "-",
                "category": "面部护理/C全方位特效小护理",
                "brandStoreName": null
            },
            {
                "id": "8787426654181114664",
                "date": "2017-03-26",
                "customerName": "路*(L20033)",
                "customerType": "体验客",
                "storeName": "天子娇子嘉信店",
                "code": "201703262000104207527569",
                "serverProduct": "B1b能量舒压背部疗法",
                "serverNumber": "1",
                "roomName": "A2",
                "useCard": "B1B能量舒压背部疗法20次",
                "storeConsume": "90.00",
                "giftConsume": "0.00",
                "openEmp": "莫*盈",
                "des": "",
                "workEmpList": [
                    {
                        "empName": "陈*琴",
                        "postType": "高级技师",
                        "consumeAch": "90.00",
                        "commission": "0.00",
                        "extrawage": "0.00",
                        "isAppont": "0"
                    },
                    {
                        "empName": "莫*盈",
                        "postType": "高级顾问",
                        "consumeAch": "90.00",
                        "commission": "0.00",
                        "extrawage": "0.00",
                        "isAppont": "0"
                    }
                ],
                "orderType": "0",
                "inviters": null,
                "sourceName": null,
                "evaluateValue": null,
                "evaluteDes": "-",
                "isFix": "0",
                "advisor": "莫*盈",
                "beautician": "陈*琴",
                "category": "身体养生/B1b能量舒压背部疗法",
                "brandStoreName": null
            },
            {
                "id": "8787426654103502272",
                "date": "2017-03-26",
                "customerName": "梁*珍(L20089)",
                "customerType": "体验客",
                "storeName": "天子娇子嘉信店",
                "code": "201703261927334316772268",
                "serverProduct": "(B21c)肠胃保养",
                "serverNumber": "1",
                "roomName": "V3",
                "useCard": "御灸50次",
                "storeConsume": "0.00",
                "giftConsume": "0.00",
                "openEmp": "莫*盈",
                "des": "",
                "workEmpList": [
                    {
                        "empName": "文*",
                        "postType": "高级技师",
                        "consumeAch": "0.00",
                        "commission": "0.00",
                        "extrawage": "0.00",
                        "isAppont": "0"
                    },
                    {
                        "empName": "陈*琴",
                        "postType": "高级技师",
                        "consumeAch": "0.00",
                        "commission": "0.00",
                        "extrawage": "0.00",
                        "isAppont": "0"
                    },
                    {
                        "empName": "陈*香",
                        "postType": "高级顾问",
                        "consumeAch": "0.00",
                        "commission": "0.00",
                        "extrawage": "0.00",
                        "isAppont": "0"
                    }
                ],
                "orderType": "1",
                "inviters": null,
                "sourceName": null,
                "evaluateValue": null,
                "evaluteDes": "-",
                "isFix": "0",
                "advisor": "陈*香",
                "beautician": "-",
                "category": "身体护理/B21御灸理疗",
                "brandStoreName": null
            },
            {
                "id": "8787426654103502268",
                "date": "2017-03-26",
                "customerName": "梁*珍(L20089)",
                "customerType": "体验客",
                "storeName": "天子娇子嘉信店",
                "code": "201703261927334316772268",
                "serverProduct": "(B21f)御灸腿部疗法",
                "serverNumber": "1",
                "roomName": "V3",
                "useCard": "御灸50次",
                "storeConsume": "0.00",
                "giftConsume": "0.00",
                "openEmp": "莫*盈",
                "des": "",
                "workEmpList": [
                    {
                        "empName": "文*",
                        "postType": "高级技师",
                        "consumeAch": "0.00",
                        "commission": "0.00",
                        "extrawage": "0.00",
                        "isAppont": "0"
                    },
                    {
                        "empName": "陈*琴",
                        "postType": "高级技师",
                        "consumeAch": "0.00",
                        "commission": "0.00",
                        "extrawage": "0.00",
                        "isAppont": "0"
                    },
                    {
                        "empName": "陈*香",
                        "postType": "高级顾问",
                        "consumeAch": "0.00",
                        "commission": "0.00",
                        "extrawage": "0.00",
                        "isAppont": "0"
                    }
                ],
                "orderType": "1",
                "inviters": null,
                "sourceName": null,
                "evaluateValue": null,
                "evaluteDes": "-",
                "isFix": "0",
                "advisor": "陈*香",
                "beautician": "-",
                "category": "身体护理/B21御灸理疗",
                "brandStoreName": null
            },
            {
                "id": "8787426654103502264",
                "date": "2017-03-26",
                "customerName": "梁*珍(L20089)",
                "customerType": "体验客",
                "storeName": "天子娇子嘉信店",
                "code": "201703261927334316772268",
                "serverProduct": "(B21d)女性保养",
                "serverNumber": "1",
                "roomName": "V3",
                "useCard": "御灸50次",
                "storeConsume": "0.00",
                "giftConsume": "0.00",
                "openEmp": "莫*盈",
                "des": "",
                "workEmpList": [
                    {
                        "empName": "文*",
                        "postType": "高级技师",
                        "consumeAch": "0.00",
                        "commission": "0.00",
                        "extrawage": "0.00",
                        "isAppont": "0"
                    },
                    {
                        "empName": "陈*琴",
                        "postType": "高级技师",
                        "consumeAch": "0.00",
                        "commission": "0.00",
                        "extrawage": "0.00",
                        "isAppont": "0"
                    },
                    {
                        "empName": "陈*香",
                        "postType": "高级顾问",
                        "consumeAch": "0.00",
                        "commission": "0.00",
                        "extrawage": "0.00",
                        "isAppont": "0"
                    }
                ],
                "orderType": "1",
                "inviters": null,
                "sourceName": null,
                "evaluateValue": null,
                "evaluteDes": "-",
                "isFix": "0",
                "advisor": "陈*香",
                "beautician": "-",
                "category": "身体护理/B21御灸理疗",
                "brandStoreName": null
            },
            {
                "id": "8787426654092728561",
                "date": "2017-03-26",
                "customerName": "梁*珍(L20089)",
                "customerType": "体验客",
                "storeName": "天子娇子嘉信店",
                "code": "201703261927334316772268",
                "serverProduct": "B30E朵娜密内分泌净化排毒疗法",
                "serverNumber": "1",
                "roomName": "V3",
                "useCard": "朵娜密排毒疗法（买一送一）",
                "storeConsume": "250.00",
                "giftConsume": "0.00",
                "openEmp": "莫*盈",
                "des": "",
                "workEmpList": [
                    {
                        "empName": "文*",
                        "postType": "高级技师",
                        "consumeAch": "250.00",
                        "commission": "0.00",
                        "extrawage": "0.00",
                        "isAppont": "0"
                    },
                    {
                        "empName": "陈*香",
                        "postType": "高级顾问",
                        "consumeAch": "250.00",
                        "commission": "0.00",
                        "extrawage": "0.00",
                        "isAppont": "0"
                    }
                ],
                "orderType": "0",
                "inviters": null,
                "sourceName": null,
                "evaluateValue": null,
                "evaluteDes": "-",
                "isFix": "0",
                "advisor": "陈*香",
                "beautician": "-",
                "category": "身体养生/B30朵娜密内分泌疗法",
                "brandStoreName": null
            },
            {
                "id": "8787426654092728558",
                "date": "2017-03-26",
                "customerName": "梁*珍(L20089)",
                "customerType": "体验客",
                "storeName": "天子娇子嘉信店",
                "code": "201703261927334316772268",
                "serverProduct": "(YF10)E光全套",
                "serverNumber": "1",
                "roomName": "V3",
                "useCard": "YF10E光全套10次",
                "storeConsume": "1176.00",
                "giftConsume": "0.00",
                "openEmp": "莫*盈",
                "des": "",
                "workEmpList": [
                    {
                        "empName": "黄*兰",
                        "postType": "高级技师",
                        "consumeAch": "1176.00",
                        "commission": "0.00",
                        "extrawage": "0.00",
                        "isAppont": "0"
                    },
                    {
                        "empName": "陈*香",
                        "postType": "高级顾问",
                        "consumeAch": "1176.00",
                        "commission": "0.00",
                        "extrawage": "0.00",
                        "isAppont": "0"
                    }
                ],
                "orderType": "0",
                "inviters": null,
                "sourceName": null,
                "evaluateValue": null,
                "evaluteDes": "-",
                "isFix": "0",
                "advisor": "陈*香",
                "beautician": "-",
                "category": "抗衰老/YF全方位面部抗衰仪器",
                "brandStoreName": null
            },
            {
                "id": "8787426654092728555",
                "date": "2017-03-26",
                "customerName": "梁*珍(L20089)",
                "customerType": "体验客",
                "storeName": "天子娇子嘉信店",
                "code": "201703261927334316772268",
                "serverProduct": "(B26E)谷物",
                "serverNumber": "1",
                "roomName": "V3",
                "useCard": "B26E谷物",
                "storeConsume": "240.00",
                "giftConsume": "0.00",
                "openEmp": "莫*盈",
                "des": "",
                "workEmpList": [
                    {
                        "empName": "黄*兰",
                        "postType": "高级技师",
                        "consumeAch": "240.00",
                        "commission": "0.00",
                        "extrawage": "0.00",
                        "isAppont": "0"
                    },
                    {
                        "empName": "陈*香",
                        "postType": "高级顾问",
                        "consumeAch": "240.00",
                        "commission": "0.00",
                        "extrawage": "0.00",
                        "isAppont": "0"
                    }
                ],
                "orderType": "1",
                "inviters": null,
                "sourceName": null,
                "evaluateValue": null,
                "evaluteDes": "-",
                "isFix": "0",
                "advisor": "陈*香",
                "beautician": "-",
                "category": "身体护理/B26结肠SPA-自然疗法",
                "brandStoreName": null
            },
            {
                "id": "8787426654092728552",
                "date": "2017-03-26",
                "customerName": "梁*珍(L20089)",
                "customerType": "体验客",
                "storeName": "天子娇子嘉信店",
                "code": "201703261927334316772268",
                "serverProduct": "(B26a)结肠",
                "serverNumber": "1",
                "roomName": "V3",
                "useCard": "B26a结肠12次",
                "storeConsume": "406.67",
                "giftConsume": "0.00",
                "openEmp": "莫*盈",
                "des": "",
                "workEmpList": [
                    {
                        "empName": "黄*兰",
                        "postType": "高级技师",
                        "consumeAch": "406.67",
                        "commission": "0.00",
                        "extrawage": "0.00",
                        "isAppont": "0"
                    },
                    {
                        "empName": "陈*香",
                        "postType": "高级顾问",
                        "consumeAch": "406.67",
                        "commission": "0.00",
                        "extrawage": "0.00",
                        "isAppont": "0"
                    }
                ],
                "orderType": "1",
                "inviters": null,
                "sourceName": null,
                "evaluateValue": null,
                "evaluteDes": "-",
                "isFix": "0",
                "advisor": "陈*香",
                "beautician": "-",
                "category": "身体护理/B26结肠SPA-自然疗法",
                "brandStoreName": null
            },
            {
                "id": "8787426654092728549",
                "date": "2017-03-26",
                "customerName": "梁*珍(L20089)",
                "customerType": "体验客",
                "storeName": "天子娇子嘉信店",
                "code": "201703261927334316772268",
                "serverProduct": "B3c宫廷养生药浴",
                "serverNumber": "1",
                "roomName": "V3",
                "useCard": "B3c宫廷养生药浴10次",
                "storeConsume": "138.00",
                "giftConsume": "0.00",
                "openEmp": "莫*盈",
                "des": "",
                "workEmpList": [
                    {
                        "empName": "黄*兰",
                        "postType": "高级技师",
                        "consumeAch": "138.00",
                        "commission": "0.00",
                        "extrawage": "0.00",
                        "isAppont": "0"
                    },
                    {
                        "empName": "陈*香",
                        "postType": "高级顾问",
                        "consumeAch": "138.00",
                        "commission": "0.00",
                        "extrawage": "0.00",
                        "isAppont": "0"
                    }
                ],
                "orderType": "0",
                "inviters": null,
                "sourceName": null,
                "evaluateValue": null,
                "evaluteDes": "-",
                "isFix": "0",
                "advisor": "陈*香",
                "beautician": "-",
                "category": "SPA泡浴/B3泡浴养生",
                "brandStoreName": null
            },
            {
                "id": "8787426654065508736",
                "date": "2017-03-26",
                "customerName": "候*梅(H20048)",
                "customerType": "体验客",
                "storeName": "天子娇子嘉信店",
                "code": "201703261917230530246156",
                "serverProduct": "AF1清新清爽补水护理",
                "serverNumber": "1",
                "roomName": "-",
                "useCard": "AF1清新清爽补水护理.10次",
                "storeConsume": "180.00",
                "giftConsume": "0.00",
                "openEmp": "莫*盈",
                "des": "",
                "workEmpList": [
                    {
                        "empName": "陈*琴",
                        "postType": "高级技师",
                        "consumeAch": "180.00",
                        "commission": "0.00",
                        "extrawage": "0.00",
                        "isAppont": "0"
                    },
                    {
                        "empName": "莫*盈",
                        "postType": "高级顾问",
                        "consumeAch": "180.00",
                        "commission": "0.00",
                        "extrawage": "0.00",
                        "isAppont": "0"
                    }
                ],
                "orderType": "0",
                "inviters": null,
                "sourceName": null,
                "evaluateValue": null,
                "evaluteDes": "-",
                "isFix": "0",
                "advisor": "莫*盈",
                "beautician": "闰*",
                "category": "面部护理/AF日本奥比虹品牌",
                "brandStoreName": null
            },
            {
                "id": "8787426654060699914",
                "date": "2017-03-26",
                "customerName": "区*鸣(O1001)",
                "customerType": "体验客",
                "storeName": "天子娇子嘉信店",
                "code": "201703261916636169424997",
                "serverProduct": "B20b五十肩手臂手指护理",
                "serverNumber": "1",
                "roomName": "A2",
                "useCard": "B20B",
                "storeConsume": "298.00",
                "giftConsume": "0.00",
                "openEmp": "莫*盈",
                "des": "",
                "workEmpList": [
                    {
                        "empName": "陈*香",
                        "postType": "高级顾问",
                        "consumeAch": "298.00",
                        "commission": "0.00",
                        "extrawage": "0.00",
                        "isAppont": "0"
                    },
                    {
                        "empName": "少*",
                        "postType": "高级技师",
                        "consumeAch": "298.00",
                        "commission": "0.00",
                        "extrawage": "0.00",
                        "isAppont": "0"
                    }
                ],
                "orderType": "0",
                "inviters": null,
                "sourceName": null,
                "evaluateValue": null,
                "evaluteDes": "-",
                "isFix": "0",
                "advisor": "陈*香",
                "beautician": "-",
                "category": "身体养生/B20养骨系列",
                "brandStoreName": null
            },
            {
                "id": "8787426654060696056",
                "date": "2017-03-26",
                "customerName": "区*鸣(O1001)",
                "customerType": "体验客",
                "storeName": "天子娇子嘉信店",
                "code": "201703261916636169424997",
                "serverProduct": "AF1清新清爽补水护理",
                "serverNumber": "1",
                "roomName": "A2",
                "useCard": "AF1清新清爽补水护理.10次",
                "storeConsume": "180.00",
                "giftConsume": "0.00",
                "openEmp": "莫*盈",
                "des": "",
                "workEmpList": [
                    {
                        "empName": "陈*香",
                        "postType": "高级顾问",
                        "consumeAch": "180.00",
                        "commission": "0.00",
                        "extrawage": "0.00",
                        "isAppont": "0"
                    },
                    {
                        "empName": "少*",
                        "postType": "高级技师",
                        "consumeAch": "180.00",
                        "commission": "0.00",
                        "extrawage": "0.00",
                        "isAppont": "0"
                    }
                ],
                "orderType": "0",
                "inviters": null,
                "sourceName": null,
                "evaluateValue": null,
                "evaluteDes": "-",
                "isFix": "0",
                "advisor": "陈*香",
                "beautician": "-",
                "category": "面部护理/AF日本奥比虹品牌",
                "brandStoreName": null
            },
            {
                "id": "8787426654060693019",
                "date": "2017-03-26",
                "customerName": "区*鸣(O1001)",
                "customerType": "体验客",
                "storeName": "天子娇子嘉信店",
                "code": "201703261916636169424997",
                "serverProduct": "E1五子青春明目护理",
                "serverNumber": "1",
                "roomName": "A2",
                "useCard": "E1五子青春明目护理10次",
                "storeConsume": "88.00",
                "giftConsume": "0.00",
                "openEmp": "莫*盈",
                "des": "",
                "workEmpList": [
                    {
                        "empName": "陈*香",
                        "postType": "高级顾问",
                        "consumeAch": "88.00",
                        "commission": "0.00",
                        "extrawage": "0.00",
                        "isAppont": "0"
                    },
                    {
                        "empName": "少*",
                        "postType": "高级技师",
                        "consumeAch": "88.00",
                        "commission": "0.00",
                        "extrawage": "0.00",
                        "isAppont": "0"
                    }
                ],
                "orderType": "0",
                "inviters": null,
                "sourceName": null,
                "evaluateValue": null,
                "evaluteDes": "-",
                "isFix": "0",
                "advisor": "陈*香",
                "beautician": "-",
                "category": "眼部护理/E眼部抗衰护理",
                "brandStoreName": null
            },
            {
                "id": "8787426653475791080",
                "date": "2017-03-26",
                "customerName": "陈*仙(c20014)",
                "customerType": "普通会员",
                "storeName": "天子娇子嘉信店",
                "code": "201703261458102555372562",
                "serverProduct": "B1b能量舒压背部疗法",
                "serverNumber": "1",
                "roomName": "V3",
                "useCard": "B1b能量舒压背部疗法",
                "storeConsume": "10.00",
                "giftConsume": "0.00",
                "openEmp": "莫*盈",
                "des": "",
                "workEmpList": [
                    {
                        "empName": "总*美",
                        "postType": "高级技师",
                        "consumeAch": "10.00",
                        "commission": "0.00",
                        "extrawage": "0.00",
                        "isAppont": "0"
                    }
                ],
                "orderType": "0",
                "inviters": null,
                "sourceName": null,
                "evaluateValue": null,
                "evaluteDes": "-",
                "isFix": "0",
                "advisor": "陈*香",
                "beautician": "-",
                "category": "身体养生/B1b能量舒压背部疗法",
                "brandStoreName": null
            }
        ],
        "pageNum": 1
    }
}
export default data;